In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *

In [2]:
spark = SparkSession.builder.appName("teste3").getOrCreate()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/06/26 21:33:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/06/26 21:33:10 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
24/06/26 21:33:10 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.

In [14]:
schema = StructType([
    StructField("id", LongType(), True), 
    StructField("valor", FloatType(), True),
    StructField("mes_competencia", IntegerType(), True)
    ])

In [15]:
df = spark.read.schema(schema).parquet("assets/data/valores/valores.parquet")

In [16]:
df.show()

+-----------+------+---------------+
|         id| valor|mes_competencia|
+-----------+------+---------------+
|16404626188| 440.0|         202311|
|12855432938| 700.0|         202311|
|12515719645| 600.0|         202311|
|20141877027| 716.0|         202311|
|12754504046| 750.0|         202311|
|16327311882| 300.0|         202311|
|20734949175| 300.0|         202311|
|13277350818| 255.0|         202311|
|23860560715| 600.0|         202311|
|16081555004| 640.0|         202311|
|20392393993| 325.0|         202311|
|16034808716| 850.0|         202311|
|16109517985| 800.0|         202311|
|16696523309|1018.0|         202311|
|13385107775| 800.0|         202311|
|20649773548| 540.0|         202311|
|23600245321| 750.0|         202311|
|20934562029| 300.0|         202311|
|21313038581| 650.0|         202311|
|21304357017|1302.0|         202311|
+-----------+------+---------------+
only showing top 20 rows

In [17]:
df.createOrReplaceTempView("valores")

In [21]:
spark.sql("""SELECT * 
          FROM valores 
          WHERE id in (
            20128077306,
            21352016526,
            16358953061,
            13622350775,
            20418689428,
            20732189858,
            20381458983,
            20789861660,
            20429555924,
            16076155060,
            12102260099,
            20128077306,
            16358953061,
            13642886859,
            20030724885,
            13622350775,
            16117315733,
            20373408891,
            13548762890)""").show(100,truncate=False)

+-----------+-----+---------------+
|id         |valor|mes_competencia|
+-----------+-----+---------------+
|20732189858|950.0|202311         |
|20732189858|950.0|202311         |
|13548762890|600.0|202311         |
|20789861660|900.0|202311         |
|20789861660|900.0|202311         |
|16117315733|490.0|202311         |
|12102260099|600.0|202311         |
|12102260099|600.0|202311         |
|13622350775|325.0|202311         |
|13622350775|325.0|202311         |
|20030724885|551.0|202311         |
|20418689428|300.0|202311         |
|16076155060|850.0|202311         |
|16076155060|850.0|202311         |
|20128077306|750.0|202311         |
|20128077306|750.0|202311         |
|16076155060|950.0|202311         |
|16358953061|650.0|202311         |
|16358953061|650.0|202311         |
|20732189858|950.0|202311         |
|20789861660|900.0|202311         |
|20789861660|900.0|202311         |
|20030724885|391.0|202311         |
|12102260099|600.0|202311         |
|13622350775|325.0|202311         |
|13622350775|325.0|202311         |
|20030724885|551.0|202311         |
|20030724885|551.0|202311         |
|16076155060|850.0|202311         |
|20128077306|750.0|202311         |
|20128077306|750.0|202311         |
|20373408891|600.0|202311         |
|16358953061|650.0|202311         |
|16358953061|650.0|202311         |
|20732189858|950.0|202311         |
|20732189858|950.0|202311         |
|20429555924|600.0|202311         |
|13642886859|363.0|202311         |
|20789861660|900.0|202311         |
|12102260099|600.0|202311         |
|12102260099|600.0|202311         |
|13622350775|325.0|202311         |
|20030724885|551.0|202311         |
|16076155060|850.0|202311         |
|16076155060|850.0|202311         |
|20128077306|750.0|202311         |
|20128077306|750.0|202311         |
|16358953061|650.0|202311         |
|21352016526|600.0|202311         |
|20732189858|950.0|202311         |
|20732189858|950.0|202311         |
|20789861660|900.0|202311         |
|20789861660|900.0|202311         |
|12102260099|600.0|202311         |
|12102260099|600.0|202311         |
|13622350775|325.0|202311         |
|13622350775|325.0|202311         |
|20030724885|551.0|202311         |
|20030724885|551.0|202311         |
|16076155060|850.0|202311         |
|20128077306|750.0|202311         |
|20128077306|750.0|202311         |
|20381458983|490.0|202311         |
|16358953061|650.0|202311         |
|16358953061|650.0|202311         |
|20732189858|950.0|202311         |
|20732189858|950.0|202311         |
|20789861660|900.0|202311         |
|20789861660|900.0|202311         |
|12102260099|600.0|202311         |
|13622350775|325.0|202311         |
|13622350775|325.0|202311         |
|20030724885|551.0|202311         |
|16076155060|850.0|202311         |
|16076155060|850.0|202311         |
|20128077306|750.0|202311         |
|16358953061|650.0|202311         |
+-----------+-----+---------------+